### ISSUE TITLE
Business analysis of volunteer validation

### ISSUE THREAD

**Issue by R-accoo-n** [R-accoo-n/Nameless-volunteer-project#7]
Analysis of volunteer validation, search for existing solutions and possibilities of their implementation in the project

**Comment by nazardyda** [comment]
[Стати волонтером — Добрий Самарянин.pdf](https://github.com/R-accoo-n/Nameless-volunteer-project/files/10832299/default.pdf)
//Your application has been written and submitted, so it is most likely checked by a person from the organization.

[Стати волонтером – Kiddo.pdf](https://github.com/R-accoo-n/Nameless-volunteer-project/files/10832314/Kiddo.pdf)
//Fill out the form and receive a letter about cooperation from our coordinator, so it is most likely checked by a person from the organization. 

[Сторінка Проекту Волонтерство _ Проекти - Благодійний фонд _Рідні_.pdf](https://github.com/R-accoo-n/Nameless-volunteer-project/files/10832356/_.-._._.pdf)
//Write to us at [Facebook ](https://www.facebook.com/RIDNIcommunity)або [Instagram](https://www.instagram.com/ridni.community/). So it is most likely checked by a person from the organization.

[Долучайся до допомоги_ Українська Волонтерська Служба закликає ставати волонтерами та допомагати військовим.pdf](https://github.com/R-accoo-n/Nameless-volunteer-project/files/10832372/_.pdf)
//It is most likely checked by a person from the organization.

Conclusion. Each organization verifies the data itself (perhaps it is worth checking the passport + volunteering document and after that contact the organization for confirmation)
